### PR TITLE
Fixed tests for cuda 11

### PR DESCRIPTION
**Pull request by npanpaliya**
## Checklist before submitting

- [x] Did you read the [contributor guide](https://github.com/open-ce/open-ce/blob/master/CONTRIBUTING.md)?
- [ ] Did you update any affected [documentation](https://github.com/open-ce/open-ce/blob/master/doc/)?
- [ ] Did you write any [tests](https://github.com/open-ce/open-ce/blob/master/tests/) to validate this change?  

## Description

With cuda 11.0, we need this additional change for the tests to work. With cuda 10.2, I didn't need dask to run the tests.

## Review process to land 

1. All tests and other checks must succeed.
2. At least one [maintainer](https://github.com/open-ce/open-ce/blob/master/MAINTAINERS.md) must review and approve.
3. If any  [maintainer](https://github.com/open-ce/open-ce/blob/master/MAINTAINERS.md) requests changes, they must be addressed.

### CODE REVIEW

**Review by cdeepali — APPROVED** [review]

**Review by jayfurmanek — APPROVED** [review]

**Comment by npanpaliya** [comment]
I've been running all the combinations today and found that one tests fail specifically with py36 irrespective of cuda version.
```
=================================== FAILURES ===================================
______________________________ test_with_asyncio _______________________________

    def test_with_asyncio():
        with LocalCluster() as cluster:
            with Client(cluster) as client:
                address = client.scheduler.address
>               output = asyncio.run(run_from_dask_array_asyncio(address))
E               AttributeError: module 'asyncio' has no attribute 'run'

tests/python/test_with_dask.py:542: AttributeError
```
As per the documentation, asyncio.run function was added in Py3.7 as per https://docs.python.org/3/library/asyncio-task.html#asyncio.run. So, this will not work with py3.6.
I think we should disable this test for py3.6.

**Review by bnemanich — APPROVED** [review]
